// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

/*
Package hello is a generated protocol buffer package.

It is generated from these files:
	hello.proto

It has these top-level messages:
	GetHelloRequest
	GetHelloResponse
	GetProfileRequest
	GetProfileResponse
*/
package hello

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetHelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetHelloRequest) Reset()                    { *m = GetHelloRequest{} }
func (m *GetHelloRequest) String() string            { return proto.CompactTextString(m) }
func (*GetHelloRequest) ProtoMessage()               {}
func (*GetHelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetHelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetHelloResponse struct {
	Greeting string `protobuf:"bytes,1,opt,name=greeting" json:"greeting,omitempty"`
}

func (m *GetHelloResponse) Reset()                    { *m = GetHelloResponse{} }
func (m *GetHelloResponse) String() string            { return proto.CompactTextString(m) }
func (*GetHelloResponse) ProtoMessage()               {}
func (*GetHelloResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetHelloResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type GetProfileRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
}

func (m *GetProfileRequest) Reset()                    { *m = GetProfileRequest{} }
func (m *GetProfileRequest) String() string            { return proto.CompactTextString(m) }
func (*GetProfileRequest) ProtoMessage()               {}
func (*GetProfileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetProfileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetProfileRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type GetProfileResponse struct {
	Info string `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *GetProfileResponse) Reset()                    { *m = GetProfileResponse{} }
func (m *GetProfileResponse) String() string            { return proto.CompactTextString(m) }
func (*GetProfileResponse) ProtoMessage()               {}
func (*GetProfileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetProfileResponse) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func init() {
	proto.RegisterType((*GetHelloRequest)(nil), "GetHelloRequest")
	proto.RegisterType((*GetHelloResponse)(nil), "GetHelloResponse")
	proto.RegisterType((*GetProfileRequest)(nil), "GetProfileRequest")
	proto.RegisterType((*GetProfileResponse)(nil), "GetProfileResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Hello service

type HelloClient interface {
	GetHello(ctx context.Context, in *GetHelloRequest, opts ...grpc.CallOption) (*GetHelloResponse, error)
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) GetHello(ctx context.Context, in *GetHelloRequest, opts ...grpc.CallOption) (*GetHelloResponse, error) {
	out := new(GetHelloResponse)
	err := grpc.Invoke(ctx, "/Hello/GetHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	out := new(GetProfileResponse)
	err := grpc.Invoke(ctx, "/Hello/GetProfile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hello service

type HelloServer interface {
	GetHello(context.Context, *GetHelloRequest) (*GetHelloResponse, error)
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_GetHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).GetHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Hello/GetHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).GetHello(ctx, req.(*GetHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hello_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Hello/GetProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHello",
			Handler:    _Hello_GetHello_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _Hello_GetProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x0b, 0x82, 0x40,
	0x10, 0x85, 0xb5, 0x34, 0x6c, 0x3a, 0xa4, 0xd3, 0x45, 0x3c, 0xc9, 0x42, 0xe0, 0x69, 0xa1, 0x3a,
	0x44, 0xbf, 0xc0, 0x8e, 0xe1, 0x3f, 0x30, 0x18, 0x4d, 0xb0, 0x5d, 0x73, 0xb7, 0xff, 0x1f, 0x2e,
	0x9a, 0xa1, 0xd0, 0xed, 0xed, 0xf2, 0xde, 0xbc, 0x6f, 0x06, 0x36, 0x0f, 0xaa, 0x6b, 0xc9, 0x9b,
	0x56, 0x6a, 0xc9, 0xf6, 0xb0, 0x4d, 0x49, 0x5f, 0xbb, 0x9f, 0x8c, 0x5e, 0x6f, 0x52, 0x1a, 0x11,
	0x1c, 0x91, 0x3f, 0x29, 0xb4, 0x63, 0x3b, 0x59, 0x67, 0x46, 0x33, 0x0e, 0xfe, 0x68, 0x53, 0x8d,
	0x14, 0x8a, 0x30, 0x02, 0xaf, 0x6c, 0x89, 0x74, 0x25, 0xca, 0xde, 0xfb, 0x7d, 0xb3, 0x0b, 0x04,
	0x29, 0xe9, 0x5b, 0x2b, 0x8b, 0xaa, 0xa6, 0x3f, 0x83, 0xd1, 0x87, 0x65, 0x5e, 0x52, 0xb8, 0x88,
	0xed, 0xc4, 0xcd, 0x3a, 0xc9, 0x12, 0xc0, 0xdf, 0x68, 0x5f, 0x86, 0xe0, 0x54, 0xa2, 0x90, 0x43,
	0xb6, 0xd3, 0x47, 0x05, 0xae, 0x21, 0xc2, 0x03, 0x78, 0x03, 0x1d, 0xfa, 0x7c, 0xb2, 0x4f, 0x14,
	0xf0, 0x29, 0x3a, 0xb3, 0xf0, 0x0c, 0x30, 0xb6, 0x20, 0xf2, 0x19, 0x6d, 0xb4, 0xe3, 0x73, 0x0c,
	0x66, 0xdd, 0x57, 0xe6, 0x6e, 0xa7, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x70, 0x92, 0xdf, 0xb4,
	0x46, 0x01, 0x00, 0x00,
}
